# Generated by Django 4.2 on 2024-08-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_comment_user_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product/%Y/%m/%d/'),
        ),
    ]
