# Generated by Django 4.2 on 2024-08-06 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.ManyToManyField(related_name='vendors', to=settings.AUTH_USER_MODEL),
        ),
    ]
