# Generated by Django 4.2 on 2024-08-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendorimage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorimage',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product/%Y/%m/%d/'),
        ),
    ]
