# Generated by Django 4.2 on 2024-08-24 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendorimage_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorimage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vendors.vendor'),
        ),
    ]
