# Generated by Django 4.2 on 2024-08-28 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendor_average_rating_vendor_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
