# Generated by Django 4.2 on 2024-08-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
