# Generated by Django 4.2 on 2024-09-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_is_paid_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('shipped', 'Shipped')], default='pending', max_length=10),
        ),
    ]
